name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          check-latest: true
      - name: Install deps
        run: go mod download
      - name: Run tests
        run: go test -v ./...
      - name: Run lint
        uses: golangci/golangci-lint-action@v6.1.1
